---
version: "3.3"
services:
  gluetun:
    container_name: GlueTun-VPN
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 51820:51820
      - 51820:51820/udp
      - 46931:46931
      - 46931:46931/udp
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=${ENDPOINT_IP}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDR}
      - VPN_ENDPOINT_PORT=${ENDPOINT_PORT}
      - VPN_DNS_ADDRESS=${DNS_ADDRESS}
      - WIREGUARD_PUBLIC_KEY=${PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${PRIVATE_KEY}
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING_STATUS_FILE=/tmp/gluetun/forwarded_port
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
    restart: always
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}
        target:${COMMON_PATH}
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/gluetun
        target:/tmp/gluetun
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: service:gluetun
    container_name: qbittorrent
    depends_on:
      - gluetun
    environment:
      - WEBUI_PORT=8080
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      #- DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}
        target:${COMMON_PATH}
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/configs/qbittorrent
        target:/config 
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/qbittorrent/downloads
        target:/downloads
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      #- LANG=fr_FR
      #- LANG=en_US
    ports:
      - 8191:8191
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/configs/prowlarr
        target:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/configs/jackett
        target:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}
        target:${COMMON_PATH}
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/configs/sonarr
        target:/config 
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/sonarr/tv
        target:/tv
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/qbittorrent/downloads
        target:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}
        target:${COMMON_PATH}
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/configs/radarr
        target:/config 
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/radarr/movies
        target:/movies
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/qbittorrent/downloads
        target:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}
        target:${COMMON_PATH}
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/configs/jellyfin
        target:/config 
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/jellyfin/cache
        target:/cache
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/sonarr/tv
        target:/media/tv
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/radarr/movies
        target:/media/movies
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/qbittorrent/downloads
        target:/media/downloads
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - type:bind
        source:/dockerhdd/${COMMON_PATH}/configs/jellyseerr
        target:/app/config 
    restart: unless-stopped
